<a href="https://colab.research.google.com/github/WESTZERO115/childmeal/blob/main/foodnutrtion_to_mysql_ver1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 2.2 MB/s
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

In [2]:
import json
import requests

myKey = "95ec7adda481472f8165"
dataType = "json"
startNum = "1"
endNum = "10"

url = 'http://openapi.foodsafetykorea.go.kr/api/'+myKey+'/I2790/'+dataType+'/'+startNum+'/'+endNum  #식품영양정보DB/공공API/keyvalue/DBID/type/시작value/끝value 

res = requests.get(url)
res.encoding = 'UTF-8'
res_message = res.text

print(res_message)
data = json.loads(res_message)

## print(json.dumps(data, ensure_ascii=False, indent=2)) # ensure_ascii=False --> json 파일 호출시 한글 깨짐 방지

foods = data["I2790"]["row"]
food_list=[]
i=1
for food in foods:
    food_code = food["FOOD_CD"]
    food_menu = food["DESC_KOR"]
    food_groupname = food["GROUP_NAME"]
    if food_groupname == '':
        food_groupname = '식품군 정보없음'
    food_servingsize = food["SERVING_SIZE"]
    if food_servingsize == '':
        food_servingsize = '총 내용량 정보없음'
    food_kcal = food["NUTR_CONT1"]
    if food_kcal == '':
        food_kcal = '열량(kcal)(1회제공량당) 정보없음'
    food_carbohyd = food["NUTR_CONT2"]
    if food_carbohyd == '':
        food_carbohyd = '탄수화물(g)(1회제공량당) 정보없음'
    food_protein = food["NUTR_CONT3"]
    if food_protein == '':
        food_protein = '단백질(g)(1회제공량당) 정보없음'
    food_fat = food["NUTR_CONT4"]
    if food_fat == '':
        food_fat = '지방(g)(1회제공량당) 정보없음'
    food_sugars = food["NUTR_CONT5"]
    if food_sugars == '':
        food_sugars = '당류(g)(1회제공량당) 정보없음'
    food_natrium = food["NUTR_CONT6"]
    if food_natrium == '':
        food_natrium = '나트륨(mg)(1회제공량당) 정보없음'
    food_cholesterol = food["NUTR_CONT7"]
    if food_cholesterol == '':
        food_cholesterol = '콜레스테롤(mg)(1회제공량당) 정보없음'
    food_saturatedfatty = food["NUTR_CONT8"]
    if food_saturatedfatty == '':
        food_saturatedfatty = '포화지방산(g)(1회제공량당) 정보없음'
    food_transfat = food["NUTR_CONT9"]
    if food_transfat == '':
        food_transfat = '트랜스지방(g)(1회제공량당) 정보없음'

    food_list.append(tuple([food_code, food_menu, food_groupname, food_servingsize, food_kcal, food_carbohyd, food_protein, food_fat, food_sugars, food_natrium, food_cholesterol, food_saturatedfatty, food_transfat]))
    i+=1
    print(i)
print(food_list)

import pandas as pd

df = pd.DataFrame(food_list, columns = ['food_code', 'food_menu', 'food_groupname','food_servingsize','food_kcal','food_carbohyd','food_protein','food_fat','food_sugars','food_natrium','food_cholesterol','food_saturatedfatty','food_transfat'])
df

{"I2790":{"total_count":"90608","row":[{"NUTR_CONT8":"1.9","NUTR_CONT9":"0.1","NUTR_CONT4":"8.5","NUTR_CONT5":"16.9","NUTR_CONT6":"1264.31","NUM":"1","NUTR_CONT7":"106.18","NUTR_CONT1":"368.8","NUTR_CONT2":"39.7","SUB_REF_NAME":"식약처(\u002716) 제4권","NUTR_CONT3":"33.5","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"500","SAMPLING_REGION_NAME":"충주","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"꿩불고기","SAMPLING_REGION_CD":"94","FOOD_CD":"D000006"},{"NUTR_CONT8":"6","NUTR_CONT9":"0.2","NUTR_CONT4":"25.8","NUTR_CONT5":"21.2","NUTR_CONT6":"1535.83","NUM":"2","NUTR_CONT7":"193.4","NUTR_CONT1":"595.61","NUTR_CONT2":"44.9","SUB_REF_NAME":"식약처(\u002716) 제4권","NUTR_CONT3":"45.9","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"400","SAMPLING_REGION_NAME":"전국(대표)","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"닭갈비","SAMPLING_REGION_CD":"ZZ","FOOD_CD":"D000007"},{"NUTR_CONT8":"11.3","NUTR_CONT9":"0.3","NUTR_CONT4":"31.6","NUTR_CONT5":"8.5","NUTR_CONT6":"1016.94","NUM":"3","NUTR_CONT7":"217.67","NUTR_CONT1":"558.47","NUTR_CONT2":"23.1","SUB_REF_NAME":"식약처(\u002716) 제4권","NUTR_CONT3":"45.5","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"300","SAMPLING_REGION_NAME":"춘천","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"닭갈비","SAMPLING_REGION_CD":"66","FOOD_CD":"D000008"},{"NUTR_CONT8":"2.32","NUTR_CONT9":"0.04","NUTR_CONT4":"8.57","NUTR_CONT5":"3.15","NUTR_CONT6":"286.91","NUM":"4","NUTR_CONT7":"31.44","NUTR_CONT1":"176.72","NUTR_CONT2":"13.35","SUB_REF_NAME":"식약처(\u002712) 제1권","NUTR_CONT3":"11.56","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"70","SAMPLING_REGION_NAME":"전국(대표)","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"닭꼬치","SAMPLING_REGION_CD":"ZZ","FOOD_CD":"D000009"},{"NUTR_CONT8":"0.8","NUTR_CONT9":"0","NUTR_CONT4":"5.2","NUTR_CONT5":"11.6","NUTR_CONT6":"743.37","NUM":"5","NUTR_CONT7":"0.12","NUTR_CONT1":"184","NUTR_CONT2":"31.1","SUB_REF_NAME":"식약처(\u002717) 제5권","NUTR_CONT3":"3.1","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"100","SAMPLING_REGION_NAME":"전국(대표)","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"더덕구이","SAMPLING_REGION_CD":"ZZ","FOOD_CD":"D000010"},{"NUTR_CONT8":"3.8","NUTR_CONT9":"0.1","NUTR_CONT4":"16.5","NUTR_CONT5":"0","NUTR_CONT6":"1582.17","NUM":"6","NUTR_CONT7":"211.24","NUTR_CONT1":"397","NUTR_CONT2":"2.1","SUB_REF_NAME":"식약처(\u002715) 제3권","NUTR_CONT3":"61.1","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"250","SAMPLING_REGION_NAME":"전국(대표)","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"도미구이","SAMPLING_REGION_CD":"ZZ","FOOD_CD":"D000011"},{"NUTR_CONT8":"4.7","NUTR_CONT9":"0.1","NUTR_CONT4":"14.4","NUTR_CONT5":"4.5","NUTR_CONT6":"404.66","NUM":"7","NUTR_CONT7":"49.34","NUTR_CONT1":"240.32","NUTR_CONT2":"8.1","SUB_REF_NAME":"식약처(\u002716) 제4권","NUTR_CONT3":"19.5","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"100","SAMPLING_REGION_NAME":"서울특별시 마포구","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"돼지갈비","SAMPLING_REGION_CD":"95","FOOD_CD":"D000012"},{"NUTR_CONT8":"8.9","NUTR_CONT9":"0.2","NUTR_CONT4":"30.8","NUTR_CONT5":"0","NUTR_CONT6":"1567.94","NUM":"8","NUTR_CONT7":"198.51","NUTR_CONT1":"488","NUTR_CONT2":"0.2","SUB_REF_NAME":"식약처(\u002715) 제3권","NUTR_CONT3":"54.6","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"250","SAMPLING_REGION_NAME":"전국(대표)","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"병어구이","SAMPLING_REGION_CD":"ZZ","FOOD_CD":"D000015"},{"NUTR_CONT8":"6.6","NUTR_CONT9":"0.4","NUTR_CONT4":"25.2","NUTR_CONT5":"7.9","NUTR_CONT6":"560.71","NUM":"9","NUTR_CONT7":"68.85","NUTR_CONT1":"395.29","NUTR_CONT2":"7.8","SUB_REF_NAME":"식약처(\u002716) 제4권","NUTR_CONT3":"34.4","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"150","SAMPLING_REGION_NAME":"광양","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"불고기","SAMPLING_REGION_CD":"96","FOOD_CD":"D000016"},{"NUTR_CONT8":"3.6","NUTR_CONT9":"0.2","NUTR_CONT4":"16.2","NUTR_CONT5":"0.4","NUTR_CONT6":"124.75","NUM":"10","NUTR_CONT7":"167.07","NUTR_CONT1":"296.54","NUTR_CONT2":"11.6","SUB_REF_NAME":"식약처(\u002716) 제4권","NUTR_CONT3":"26","RESEARCH_YEAR":"2019","MAKER_NAME":"","GROUP_NAME":"","SERVING_SIZE":"100","SAMPLING_REGION_NAME":"고흥","SAMPLING_MONTH_CD":"AVG","SAMPLING_MONTH_NAME":"평균","DESC_KOR":"붕장어소금구이","SAMPLING_REGION_CD":"05","FOOD_CD":"D000017"}],"RESULT":{"MSG":"정상처리되었습니다.","CODE":"INFO-000"}}}
2
3
4
5
6
7
8
9
10
11
[('D000006', '꿩불고기', '식품군 정보없음', '500', '368.8', '39.7', '33.5', '8.5', '16.9', '1264.31', '106.18', '1.9', '0.1'), ('D000007', '닭갈비', '식품군 정보없음', '400', '595.61', '44.9', '45.9', '25.8', '21.2', '1535.83', '193.4', '6', '0.2'), ('D000008', '닭갈비', '식품군 정보없음', '300', '558.47', '23.1', '45.5', '31.6', '8.5', '1016.94', '217.67', '11.3', '0.3'), ('D000009', '닭꼬치', '식품군 정보없음', '70', '176.72', '13.35', '11.56', '8.57', '3.15', '286.91', '31.44', '2.32', '0.04'), ('D000010', '더덕구이', '식품군 정보없음', '100', '184', '31.1', '3.1', '5.2', '11.6', '743.37', '0.12', '0.8', '0'), ('D000011', '도미구이', '식품군 정보없음', '250', '397', '2.1', '61.1', '16.5', '0', '1582.17', '211.24', '3.8', '0.1'), ('D000012', '돼지갈비', '식품군 정보없음', '100', '240.32', '8.1', '19.5', '14.4', '4.5', '404.66', '49.34', '4.7', '0.1'), ('D000015', '병어구이', '식품군 정보없음', '250', '488', '0.2', '54.6', '30.8', '0', '1567.94', '198.51', '8.9', '0.2'), ('D000016', '불고기', '식품군 정보없음', '150', '395.29', '7.8', '34.4', '25.2', '7.9', '560.71', '68.85', '6.6', '0.4'), ('D000017', '붕장어소금구이', '식품군 정보없음', '100', '296.54', '11.6', '26', '16.2', '0.4', '124.75', '167.07', '3.6', '0.2')]

,food_code,food_menu,food_groupname,food_servingsize,food_kcal,food_carbohyd,food_protein,food_fat,food_sugars,food_natrium,food_cholesterol,food_saturatedfatty,food_transfat
0,D000006,꿩불고기,식품군 정보없음,500,368.8,39.7,33.5,8.5,16.9,1264.31,106.18,1.9,0.1
1,D000007,닭갈비,식품군 정보없음,400,595.61,44.9,45.9,25.8,21.2,1535.83,193.4,6,0.2
2,D000008,닭갈비,식품군 정보없음,300,558.47,23.1,45.5,31.6,8.5,1016.94,217.67,11.3,0.3
3,D000009,닭꼬치,식품군 정보없음,70,176.72,13.35,11.56,8.57,3.15,286.91,31.44,2.32,0.04
4,D000010,더덕구이,식품군 정보없음,100,184,31.1,3.1,5.2,11.6,743.37,0.12,0.8,0
5,D000011,도미구이,식품군 정보없음,250,397,2.1,61.1,16.5,0,1582.17,211.24,3.8,0.1
6,D000012,돼지갈비,식품군 정보없음,100,240.32,8.1,19.5,14.4,4.5,404.66,49.34,4.7,0.1
7,D000015,병어구이,식품군 정보없음,250,488,0.2,54.6,30.8,0,1567.94,198.51,8.9,0.2
8,D000016,불고기,식품군 정보없음,150,395.29,7.8,34.4,25.2,7.9,560.71,68.85,6.6,0.4
9,D000017,붕장어소금구이,식품군 정보없음,100,296.54,11.6,26,16.2,0.4,124.75,167.07,3.6,0.2

In [6]:
import pymysql

def mysql_save(food_list):
    conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
    cursor=conn.cursor()
    sql= "CREATE TABLE FOOD_NUTRITION(food_code VARCHAR(7),food_menu VARCHAR(10),food_groupname VARCHAR(10),food_servingsize INT,food_kcal FLOAT(5),food_carbohyd FLOAT(5),food_protein FLOAT(5),food_fat FLOAT(5),food_sugars FLOAT(5),food_natrium FLOAT(8),food_cholesterol FLOAT(6),food_saturatedfatty FLOAT(5),food_transfat FLOAT(3));" #DB생성
    cursor.execute(sql) #SQL수행
    # 테이블 생성 시 자동으로 증가하는 아이디 값 컬럼 생성하기
    # sql = "id INT AUTO_INCREMENT PRIMARY KEY"
    # 데이터 삽입
    sql = "INSERT INTO FOOD_NUTRITION(food_code,food_menu,food_groupname,food_servingsize,food_kcal,food_carbohyd,food_protein,food_fat,food_sugars,food_natrium,food_cholesterol,food_saturatedfatty,food_transfat) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);"
    cursor.executemany(sql,food_list)
    conn.commit()
    conn.close()
mysql_save(food_list)

In [10]:
conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM FOOD_NUTRITION WHERE food_menu = '불고기';") 
(food_code,food_menu,food_groupname,food_servingsize,food_kcal,food_carbohyd,food_protein,food_fat,food_sugars,food_natrium,food_cholesterol,food_saturatedfatty,food_transfat) = cursor.fetchone() 
print(f"{food_code},{food_menu},{food_groupname},{food_servingsize},{food_kcal},{food_carbohyd},{food_protein},{food_fat},{food_sugars},{food_natrium},{food_cholesterol},{food_saturatedfatty},{food_transfat}")

D000016,불고기,식품군 정보없음,150,395.29,7.8,34.4,25.2,7.9,560.71,68.85,6.6,0.4